### ISSUE TITLE
Úprava CREATE_TOPIC.PHP

### ISSUE THREAD

**Issue by WladinQ** [Kubo2/diggyshelper#11]
Pri vytvorení novej témy do kategórie je nutné pridať možnosť zmeniť ukladací formát t.j. Pridať kategóriu vo formáte: BB kodu / HTML kodu. Rovnako ako v POST_REPLY.PHP

**Comment by Kubo2** [comment]
Akurát problém sa týka podľa mňa skôr súboru `create_topic.php`, inak v pohode, fix do dh-1.5?

**Comment by WladinQ** [comment]
Ja robím úpravu designu nie PHP :D create_topic.php som ani nevidel :-P

**Comment by Kubo2** [comment]
Verzia v1.5-beta1 je už uzavretá, toto spolu s ďalšími vecami sa dostane až do dh-1.5 verzie beta2, ktorá vyjde 21. februára 2017.

**Comment by Kubo2** [comment]
Fix bude dvojaký. Quickfix pôjde do v1.5 a zabezpečí, aby bolo možné vybrať markup príspevku aj pri zakladaní témy (pre moderátorov), long-term fix zmení spôsob uloženia príspevkov v databáze a umožní bežným používateľom zvoliť si preferovaný markup, ktorý chcú používať vo svojich príspevkoch (pôjde do v1.6 alebo v1.7?).
