### ISSUE TITLE
Prepínanie vzhľadu stránky medzi light/dark

### ISSUE THREAD

**Issue by Kubo2** [Kubo2/diggyshelper#16]
Umožniť používateľovi prepínať medzi svetlým a defaultným tmavým vzhľadom webu, pričom sa nastavenie pre daný počítač alebo používateľa zachová.

- [ ] __v1.5.3__: implementovať prepínanie štýlu v js + cookie (commit?)
- [ ] __v1.6__: implementovať API pre ukladanie nastavenia štýlu na serveri (commit?)

**Comment by WladinQ** [comment]
Pred nasadenim prosim nahraj zmeni na wq.dh.net aby som skontroloval design oboch stylou. :-)

**Comment by Kubo2** [comment]
@WladinQ Ideme sa do tohto ešte púšťať alebo to už je staré a irelevantné? V skratke, chceme oba light/dark vzhľady alebo ponecháme teda iba dark?

**Comment by WladinQ** [comment]
Staci ponechat len dark, light vzhlad sa mi aj tak nepaci. :-)

Dňa 28.2.2018 8:59 AM používateľ "Kubis Fowler" <notifications@github.com>
napísal:
